"""Export the backend Lewis layout as the frontend test fixture.

The backend is the single source of Lewis coordinates. The renderer's tests must not
recompute them — that is exactly the duplication that let the old atom-count layout
survive in two places — so they read this generated file instead. Regenerate with:

    python -m scripts.export_lewis_layout_fixtures      # from backend/

`tests/test_lewis_layout.py` fails if the checked-in file has drifted from the code.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from app.services.lewis_service import build_lewis_structure

FIXTURE_PATH = Path(__file__).resolve().parents[2] / "frontend" / "src" / "test" / "fixtures" / "lewisLayouts.json"
_CURATED_PATH = Path(__file__).resolve().parents[1] / "app" / "data" / "curated_molecules.json"


def _curated_records() -> list[dict[str, Any]]:
    return json.loads(_CURATED_PATH.read_text(encoding="utf-8"))["molecules"]


def build_fixture_payload() -> dict[str, Any]:
    """Every curated species, keyed by id: the VSEPR verdict and the layout it produced."""

    molecules = {}
    for record in _curated_records():
        structure = build_lewis_structure(record)
        molecules[record["id"]] = {
            "formula": record["formula"],
            "ax_en": record["ax_en"],
            "electron_geometry": record["electron_geometry"],
            "molecular_geometry": record["molecular_geometry"],
            "bonding_domains": record["bonding_domains"],
            "lone_pair_domains": record["lone_pair_domains"],
            "atoms": [atom.model_dump() for atom in structure.atoms],
            "bonds": [bond.model_dump() for bond in structure.bonds],
            "central_atom_id": structure.central_atom_id,
        }
    return {
        "_description": "Generated by backend/scripts/export_lewis_layout_fixtures.py. Do not edit by hand.",
        "schema_version": "1.0",
        "molecules": molecules,
    }


def main() -> None:
    FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
    FIXTURE_PATH.write_text(json.dumps(build_fixture_payload(), indent=2) + "\n", encoding="utf-8")
    print(f"wrote {FIXTURE_PATH}")


if __name__ == "__main__":
    main()
