import { useState } from "react";
import PageContainer from "../components/layout/PageContainer";
import { useI18n } from "../i18n";
import { useSurvey } from "../hooks/useSurvey";

export default function SurveyPage() {
  const { t } = useI18n();
  const [consent, setConsent] = useState(false); const [phase, setPhase] = useState<"pre" | "post" | "likert">("pre"); const [q1, setQ1] = useState(3); const [q2, setQ2] = useState(3); const { submit, message, isLoading } = useSurvey();
  return <PageContainer><header className="page-intro"><p className="eyebrow">{t("survey.eyebrow")}</p><h1>{t("survey.title")}</h1><p>{t("survey.intro")}</p></header><section className="consent-card"><h2>{t("survey.consent.title")}</h2><p>{t("survey.consent.body")}</p><label className="check-control"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} /> {t("survey.consent.checkbox")}</label></section><form className="survey-form" onSubmit={(event) => { event.preventDefault(); if (consent) void submit({ session_id: localStorage.getItem("vsepr-session") || undefined, consent, phase, answers: { domain_confidence: q1, geometry_confidence: q2 } }); }}><label>{t("survey.phase.label")}<select value={phase} onChange={(event) => setPhase(event.target.value as typeof phase)}><option value="pre">{t("survey.phase.pre")}</option><option value="post">{t("survey.phase.post")}</option><option value="likert">{t("survey.phase.likert")}</option></select></label><label>{t("survey.q1")} <output>{q1}/5</output><input type="range" min="1" max="5" value={q1} onChange={(event) => setQ1(Number(event.target.value))} /></label><label>{t("survey.q2")} <output>{q2}/5</output><input type="range" min="1" max="5" value={q2} onChange={(event) => setQ2(Number(event.target.value))} /></label><button disabled={!consent || isLoading}>{isLoading ? t("survey.submitting") : t("survey.submit")}</button>{!consent && <small>{t("survey.consentRequired")}</small>}{message && <p role="status" className="success-message">{message}</p>}</form></PageContainer>;
}
