import type { AnalysisResult } from "../types/analysis";

export const waterAnalysis: AnalysisResult = {
  schema_version: "1.0",
  molecule: { id: "h2o", formula: "H2O", name_vi: "Nước", name_en: "Water", ax_en: "AX2E2", molecular_geometry: "bent", molecular_geometry_vi: "gấp khúc", review_status: "internal_golden_pending_expert_signoff", charge: 0, atom_inventory: { H: 2, O: 1 }, central_atom: "O", source: "curated", confidence: "high", pubchem_cid: null, smiles: "O" },
  lewis: { atoms: [{ id: "a0", element: "O", x: 160, y: 140, lone_pairs: 2, formal_charge: 0 }, { id: "a1", element: "H", x: 55, y: 140, lone_pairs: 0, formal_charge: 0 }, { id: "a2", element: "H", x: 265, y: 140, lone_pairs: 0, formal_charge: 0 }], bonds: [{ id: "b0", atom1_id: "a0", atom2_id: "a1", order: 1 }, { id: "b1", atom1_id: "a0", atom2_id: "a2", order: 1 }], central_atom_id: "a0", total_valence_electrons: 8, resonance_forms: 1, resonance_note_vi: null, exception_flags: { electron_deficient: false, expanded_octet: false, odd_electron: false, note_vi: null }, source: "curated", confidence: "high", review_status: "internal_golden_pending_expert_signoff" },
  vsepr: { bonding_domains: 2, lone_pair_domains: 2, steric_number: 4, ax_en: "AX2E2", electron_geometry: "tetrahedral", electron_geometry_vi: "tứ diện", molecular_geometry: "bent", molecular_geometry_vi: "gấp khúc", ideal_angle: "~104.5°", distortion_note_vi: "Hai cặp tự do nén góc.", teaching_note_vi: "Cặp electron tự do đẩy mạnh hơn.", pedagogical_hybridization: "sp³", hybridization_warning_vi: "Nhãn gần đúng." },
  properties: [{ key: "polarity", label_vi: "Nhận xét phân cực", value: "Phân cực", unit: null, provenance: "curated", verified_teaching_fact: true, note_vi: null }],
  structure3d: { format: "coordinates", atoms: [{ id: "a0", element: "O", x: 0, y: 0, z: 0 }, { id: "a1", element: "H", x: 1, y: 1, z: 1 }, { id: "a2", element: "H", x: -1, y: -1, z: 1 }], bonds: [{ atom1_id: "a0", atom2_id: "a1", order: 1 }, { atom1_id: "a0", atom2_id: "a2", order: 1 }], data: null, source: "curated_vsepr_template", is_illustrative: true, warning_vi: "Mô hình minh hoạ." },
  explanation: { formula: "H2O", level: "intermediate", language: "vi", sections: { lewis: "H2O có 8 electron.", ax_en: "AX2E2.", electron_geometry: "Tứ diện.", molecular_geometry: "Gấp khúc.", structure_property: "Phân cực.", learning_tip: "Đếm miền.", disclaimer: "Chỉ diễn giải." }, source: "deterministic_fallback", fallback_reason: "Claude chưa cấu hình.", prompt_version: "1.0", facts_validated: true },
  notices: { offline_capable: true, external_services_used: [], warnings_vi: [] },
};
