import type { AnalysisResult } from "../types/analysis";

export const waterAnalysis: AnalysisResult = {
  schema_version: "1.1",
  molecule: { id: "h2o", formula: "H2O", name_vi: "Nước", name_en: "Water", ax_en: "AX2E2", molecular_geometry: "bent", molecular_geometry_vi: "gấp khúc", review_status: "internal_golden_pending_expert_signoff", charge: 0, atom_inventory: { H: 2, O: 1 }, central_atom: "O", source: "curated", confidence: "high", pubchem_cid: null, smiles: "O", canonical_identity: null, inchi: null, inchikey: null, validation_status: "curated_verified", cache_timestamp: null, connectivity: { atoms: [{ id: "a0", element: "O" }, { id: "a1", element: "H" }, { id: "a2", element: "H" }], bonds: [{ atom1_id: "a0", atom2_id: "a1", order: 1 }, { atom1_id: "a0", atom2_id: "a2", order: 1 }], central_atom_id: "a0" } },
  lewis: { atoms: [{ id: "a0", element: "O", x: 160, y: 140, lone_pairs: 2, formal_charge: 0 }, { id: "a1", element: "H", x: 55, y: 140, lone_pairs: 0, formal_charge: 0 }, { id: "a2", element: "H", x: 265, y: 140, lone_pairs: 0, formal_charge: 0 }], bonds: [{ id: "b0", atom1_id: "a0", atom2_id: "a1", order: 1 }, { id: "b1", atom1_id: "a0", atom2_id: "a2", order: 1 }], central_atom_id: "a0", total_valence_electrons: 8, resonance_forms: 1, resonance_note_vi: null, exception_flags: { electron_deficient: false, expanded_octet: false, odd_electron: false, note_vi: null }, source: "curated", confidence: "high", review_status: "internal_golden_pending_expert_signoff" },
  vsepr: { bonding_domains: 2, lone_pair_domains: 2, steric_number: 4, ax_en: "AX2E2", electron_geometry: "tetrahedral", electron_geometry_vi: "tứ diện", molecular_geometry: "bent", molecular_geometry_vi: "gấp khúc", ideal_angle: "<109.5°", reference_angles: [{ display_label: "~104.5°", source: "VSEPR teaching reference", is_approximate: true, note_vi: null, note_en: null }], distortion_note_vi: "Hai cặp tự do nén góc.", distortion_note_en: "Two lone pairs compress the angle.", teaching_note_vi: "Cặp electron tự do đẩy mạnh hơn.", teaching_note_en: "A lone pair repels more strongly than a bonding pair.", pedagogical_hybridization: "sp³", hybridization_warning_vi: "Nhãn gần đúng.", hybridization_warning_en: "Approximate label." },
  properties: [{ key: "polarity", label_vi: "Nhận xét phân cực", value: "Phân cực", unit: null, provenance: "curated", verified_teaching_fact: true, note_vi: null }],
  structure3d: { format: "coordinates", atoms: [{ id: "a0", element: "O", x: 0, y: 0, z: 0 }, { id: "a1", element: "H", x: 1, y: 1, z: 1 }, { id: "a2", element: "H", x: -1, y: -1, z: 1 }], bonds: [{ atom1_id: "a0", atom2_id: "a1", order: 1 }, { atom1_id: "a0", atom2_id: "a2", order: 1 }], data: null, source: "idealized_vsepr", source_label: "Idealized VSEPR model", is_illustrative: true, is_computed: false, is_experimental: false, pubchem_cid: null, central_atom_id: "a0", angle_annotations: [{ id: "angle-0", atom1_id: "a1", center_atom_id: "a0", atom2_id: "a2", value_deg: 109.471, display_label: "109.5°", category: "ideal_vsepr", source: "Idealized VSEPR model", is_approximate: true, note_vi: null, note_en: null, equivalent_count: 1 }], electron_domains: [{ id: "lone-pair-0", center_atom_id: "a0", kind: "lone_pair", occupancy: 2, direction: { x: 0, y: 1, z: 0 }, position: { x: 0, y: 1.15, z: 0 }, source: "illustrative VSEPR orientation", is_illustrative: true, label_vi: "Miền cặp electron tự do (minh họa)", label_en: "Lone-pair electron domain (illustrative)" }], warning_vi: "Mô hình minh hoạ.", warning_en: "Illustrative model." },
  bond_angles: { preferred: [{ id: "curated-h2o", atom1_element: "H", center_element: "O", atom2_element: "H", atom1_id: null, center_atom_id: null, atom2_id: null, value_deg: 104.5, display_label: "~104.5°", evidence_type: "curated_reference", source_name: "Curated teaching reference", source_url: null, reference: null, phase: null, uncertainty_deg: null, is_experimental: false, is_computed: false, is_approximate: true, equivalent_count: 1 }], experimental: [], coordinate_derived: [{ id: "coordinate-angle-0", atom1_element: "H", center_element: "O", atom2_element: "H", atom1_id: "a1", center_atom_id: "a0", atom2_id: "a2", value_deg: 109.471, display_label: "109.47°", evidence_type: "ideal_vsepr", source_name: "Idealized VSEPR model", source_url: null, reference: null, phase: null, uncertainty_deg: null, is_experimental: false, is_computed: false, is_approximate: true, equivalent_count: 1 }], vsepr_prediction: [{ id: "vsepr-ax2e2", atom1_element: "H", center_element: "O", atom2_element: "H", atom1_id: null, center_atom_id: null, atom2_id: null, value_deg: null, display_label: "<109.5°", evidence_type: "ideal_vsepr", source_name: "General VSEPR prediction", source_url: null, reference: null, phase: null, uncertainty_deg: null, is_experimental: false, is_computed: false, is_approximate: true, equivalent_count: 1 }], selection_reason: "Curated molecule-specific reference preferred over illustrative coordinates." },
  explanation: { formula: "H2O", level: "intermediate", language: "vi", sections: { lewis: "H2O có 8 electron.", ax_en: "AX2E2.", electron_geometry: "Tứ diện.", molecular_geometry: "Gấp khúc.", structure_property: "Phân cực.", learning_tip: "Đếm miền.", disclaimer: "Chỉ diễn giải." }, source: "deterministic_fallback", fallback_reason: "Claude chưa cấu hình.", prompt_version: "1.0", facts_validated: true },
  notices: { offline_capable: true, external_services_used: [], warnings_vi: ["Mô hình minh hoạ.", "This record belongs to the internal golden set and is awaiting external chemistry-expert sign-off."], warnings_en: ["Illustrative model."], external_service_statuses: [] },
};
